@base_url = http://localhost:5216/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Seu nome",
    "cpf" : "12345678912"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

### Buscar um funcionário
GET {{base_url}}/funcionario/buscar/1

### Atualizar um funcionário
PUT {{base_url}}/funcionario/atualizar/2
Content-Type: application/json

{
    "nome": "Novo Nome",
    "cpf": "Novo Cpf"
}

### Deletar um funcionalio
DELETE {{base_url}}/funcionario/deletar/3

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folha/cadastrar
Content-Type: application/json

{
    "valor": 50,
    "quantidade" : 1000,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 1
}

### Obtenção de todas as folhas de pagamento
GET {{base_url}}/folha/listar

### Obtenção de uma folha de pagamento
GET {{base_url}}/folha/buscar/12345678912/10/2023

### Deletar folha de pagamento
DELETE {{base_url}}/folha/deletar/5
